name: BlockLoc
main: sh.kaden.hnmc.HackerNewsPlugin
version: 1.0.0
description: Hacker News in Minecraft.
author: webcrawls <kadenscott>
website: https://github.com/webcrawls/hnmc
api-version: '1.21.1'